using System;
namespace com.imeem.www.xsd
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.4908
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.1432.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class result
    {

        private Int64 statusCodeField;

        private string statusDescriptionField;

        private object statusDetailsField;

        private resultItem[] itemsField;

        private Int64 totalCountField;

        /// <remarks/>
        public Int64 statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        public string statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }

        /// <remarks/>
        public object statusDetails
        {
            get
            {
                return this.statusDetailsField;
            }
            set
            {
                this.statusDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public resultItem[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        public Int64 totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultItem
    {

        private string typeField;

        private string titleField;

        private string artistField;

        private string albumField;

        private string descriptionField;

        private string genreField;

        private Int64 durationField;

        private bool isSampleField;

        private object largeIconUrlField;

        private string iconUrlField;

        private string musicEmbedUrlField;

        private string maturityRatingField;

        private resultItemPlayabilityStatus playabilityStatusField;

        private string ownerIdField;

        private string postedByIdField;

        private string postedByField;

        private string postedByURLField;

        private string postedByUrlField;

        private decimal ratingField;

        private Int64 ratingCountField;

        private Int64 viewCountField;

        private string createDateField;

        private string favoriteCountField;

        private Int64 commentCountField;

        private string idField;

        private string urlField;

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        public string album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string genre
        {
            get
            {
                return this.genreField;
            }
            set
            {
                this.genreField = value;
            }
        }

        /// <remarks/>
        public Int64 duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        public bool isSample
        {
            get
            {
                return this.isSampleField;
            }
            set
            {
                this.isSampleField = value;
            }
        }

        /// <remarks/>
        public object largeIconUrl
        {
            get
            {
                return this.largeIconUrlField;
            }
            set
            {
                this.largeIconUrlField = value;
            }
        }

        /// <remarks/>
        public string iconUrl
        {
            get
            {
                return this.iconUrlField;
            }
            set
            {
                this.iconUrlField = value;
            }
        }

        /// <remarks/>
        public string musicEmbedUrl
        {
            get
            {
                return this.musicEmbedUrlField;
            }
            set
            {
                this.musicEmbedUrlField = value;
            }
        }

        /// <remarks/>
        public string maturityRating
        {
            get
            {
                return this.maturityRatingField;
            }
            set
            {
                this.maturityRatingField = value;
            }
        }

        /// <remarks/>
        public resultItemPlayabilityStatus playabilityStatus
        {
            get
            {
                return this.playabilityStatusField;
            }
            set
            {
                this.playabilityStatusField = value;
            }
        }

        /// <remarks/>
        public string ownerId
        {
            get
            {
                return this.ownerIdField;
            }
            set
            {
                this.ownerIdField = value;
            }
        }

        /// <remarks/>
        public string postedById
        {
            get
            {
                return this.postedByIdField;
            }
            set
            {
                this.postedByIdField = value;
            }
        }

        /// <remarks/>
        public string postedBy
        {
            get
            {
                return this.postedByField;
            }
            set
            {
                this.postedByField = value;
            }
        }

        /// <remarks/>
        public string postedByURL
        {
            get
            {
                return this.postedByURLField;
            }
            set
            {
                this.postedByURLField = value;
            }
        }

        /// <remarks/>
        public string postedByUrl
        {
            get
            {
                return this.postedByUrlField;
            }
            set
            {
                this.postedByUrlField = value;
            }
        }

        /// <remarks/>
        public decimal rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        /// <remarks/>
        public Int64 ratingCount
        {
            get
            {
                return this.ratingCountField;
            }
            set
            {
                this.ratingCountField = value;
            }
        }

        /// <remarks/>
        public Int64 viewCount
        {
            get
            {
                return this.viewCountField;
            }
            set
            {
                this.viewCountField = value;
            }
        }

        /// <remarks/>
        public string createDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        public string favoriteCount
        {
            get
            {
                return this.favoriteCountField;
            }
            set
            {
                this.favoriteCountField = value;
            }
        }

        /// <remarks/>
        public Int64 commentCount
        {
            get
            {
                return this.commentCountField;
            }
            set
            {
                this.commentCountField = value;
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class resultItemPlayabilityStatus
    {

        private Int64 playModeField;

        private string playLengthField;

        private string shareStateField;

        private string releaseDateField;

        private bool ownerField;

        /// <remarks/>
        public Int64 playMode
        {
            get
            {
                return this.playModeField;
            }
            set
            {
                this.playModeField = value;
            }
        }

        /// <remarks/>
        public string playLength
        {
            get
            {
                return this.playLengthField;
            }
            set
            {
                this.playLengthField = value;
            }
        }

        /// <remarks/>
        public string shareState
        {
            get
            {
                return this.shareStateField;
            }
            set
            {
                this.shareStateField = value;
            }
        }

        /// <remarks/>
        public string releaseDate
        {
            get
            {
                return this.releaseDateField;
            }
            set
            {
                this.releaseDateField = value;
            }
        }

        /// <remarks/>
        public bool owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
    }
}