using System;

namespace com.eventful.www.xsd
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.4918
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class search
    {

        private String total_itemsField;

        private String page_sizeField;

        private String page_countField;

        private String page_numberField;

        private String page_itemsField;

        private String first_itemField;

        private String last_itemField;

        private String search_timeField;

        private searchEvent[] eventsField;

        /// <remarks/>
        public String total_items
        {
            get
            {
                return this.total_itemsField;
            }
            set
            {
                this.total_itemsField = value;
            }
        }

        /// <remarks/>
        public String page_size
        {
            get
            {
                return this.page_sizeField;
            }
            set
            {
                this.page_sizeField = value;
            }
        }

        /// <remarks/>
        public String page_count
        {
            get
            {
                return this.page_countField;
            }
            set
            {
                this.page_countField = value;
            }
        }

        /// <remarks/>
        public String page_number
        {
            get
            {
                return this.page_numberField;
            }
            set
            {
                this.page_numberField = value;
            }
        }

        /// <remarks/>
        public String page_items
        {
            get
            {
                return this.page_itemsField;
            }
            set
            {
                this.page_itemsField = value;
            }
        }

        /// <remarks/>
        public String first_item
        {
            get
            {
                return this.first_itemField;
            }
            set
            {
                this.first_itemField = value;
            }
        }

        /// <remarks/>
        public String last_item
        {
            get
            {
                return this.last_itemField;
            }
            set
            {
                this.last_itemField = value;
            }
        }

        /// <remarks/>
        public String search_time
        {
            get
            {
                return this.search_timeField;
            }
            set
            {
                this.search_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("event", IsNullable = false)]
        public searchEvent[] events
        {
            get
            {
                return this.eventsField;
            }
            set
            {
                this.eventsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEvent
    {

        private string titleField;

        private string urlField;

        private string descriptionField;

        private string start_timeField;

        private object stop_timeField;

        private object tz_idField;

        private object tz_olson_pathField;

        private object tz_countryField;

        private object tz_cityField;

        private string venue_idField;

        private string venue_urlField;

        private string venue_nameField;

        private String venue_displayField;

        private string venue_addressField;

        private string city_nameField;

        private string region_nameField;

        private string region_abbrField;

        private String postal_codeField;

        private string country_nameField;

        private string country_abbr2Field;

        private string country_abbrField;

        private String latitudeField;

        private String longitudeField;

        private string geocode_typeField;

        private String all_dayField;

        private object recur_stringField;

        private String trackback_countField;

        private String calendar_countField;

        private object comment_countField;

        private String link_countField;

        private String going_countField;

        private String watching_countField;

        private string createdField;

        private string ownerField;

        private string modifiedField;

        private searchEventPerformers performersField;

        private searchEventImage imageField;

        private String privacyField;

        private object calendarsField;

        private object groupsField;

        private searchEventUser[] goingField;

        private string idField;

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string start_time
        {
            get
            {
                return this.start_timeField;
            }
            set
            {
                this.start_timeField = value;
            }
        }

        /// <remarks/>
        public object stop_time
        {
            get
            {
                return this.stop_timeField;
            }
            set
            {
                this.stop_timeField = value;
            }
        }

        /// <remarks/>
        public object tz_id
        {
            get
            {
                return this.tz_idField;
            }
            set
            {
                this.tz_idField = value;
            }
        }

        /// <remarks/>
        public object tz_olson_path
        {
            get
            {
                return this.tz_olson_pathField;
            }
            set
            {
                this.tz_olson_pathField = value;
            }
        }

        /// <remarks/>
        public object tz_country
        {
            get
            {
                return this.tz_countryField;
            }
            set
            {
                this.tz_countryField = value;
            }
        }

        /// <remarks/>
        public object tz_city
        {
            get
            {
                return this.tz_cityField;
            }
            set
            {
                this.tz_cityField = value;
            }
        }

        /// <remarks/>
        public string venue_id
        {
            get
            {
                return this.venue_idField;
            }
            set
            {
                this.venue_idField = value;
            }
        }

        /// <remarks/>
        public string venue_url
        {
            get
            {
                return this.venue_urlField;
            }
            set
            {
                this.venue_urlField = value;
            }
        }

        /// <remarks/>
        public string venue_name
        {
            get
            {
                return this.venue_nameField;
            }
            set
            {
                this.venue_nameField = value;
            }
        }

        /// <remarks/>
        public String venue_display
        {
            get
            {
                return this.venue_displayField;
            }
            set
            {
                this.venue_displayField = value;
            }
        }

        /// <remarks/>
        public string venue_address
        {
            get
            {
                return this.venue_addressField;
            }
            set
            {
                this.venue_addressField = value;
            }
        }

        /// <remarks/>
        public string city_name
        {
            get
            {
                return this.city_nameField;
            }
            set
            {
                this.city_nameField = value;
            }
        }

        /// <remarks/>
        public string region_name
        {
            get
            {
                return this.region_nameField;
            }
            set
            {
                this.region_nameField = value;
            }
        }

        /// <remarks/>
        public string region_abbr
        {
            get
            {
                return this.region_abbrField;
            }
            set
            {
                this.region_abbrField = value;
            }
        }

        /// <remarks/>
        public String postal_code
        {
            get
            {
                return this.postal_codeField;
            }
            set
            {
                this.postal_codeField = value;
            }
        }

        /// <remarks/>
        public string country_name
        {
            get
            {
                return this.country_nameField;
            }
            set
            {
                this.country_nameField = value;
            }
        }

        /// <remarks/>
        public string country_abbr2
        {
            get
            {
                return this.country_abbr2Field;
            }
            set
            {
                this.country_abbr2Field = value;
            }
        }

        /// <remarks/>
        public string country_abbr
        {
            get
            {
                return this.country_abbrField;
            }
            set
            {
                this.country_abbrField = value;
            }
        }

        /// <remarks/>
        public String latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        public String longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        public string geocode_type
        {
            get
            {
                return this.geocode_typeField;
            }
            set
            {
                this.geocode_typeField = value;
            }
        }

        /// <remarks/>
        public String all_day
        {
            get
            {
                return this.all_dayField;
            }
            set
            {
                this.all_dayField = value;
            }
        }

        /// <remarks/>
        public object recur_string
        {
            get
            {
                return this.recur_stringField;
            }
            set
            {
                this.recur_stringField = value;
            }
        }

        /// <remarks/>
        public String trackback_count
        {
            get
            {
                return this.trackback_countField;
            }
            set
            {
                this.trackback_countField = value;
            }
        }

        /// <remarks/>
        public String calendar_count
        {
            get
            {
                return this.calendar_countField;
            }
            set
            {
                this.calendar_countField = value;
            }
        }

        /// <remarks/>
        public object comment_count
        {
            get
            {
                return this.comment_countField;
            }
            set
            {
                this.comment_countField = value;
            }
        }

        /// <remarks/>
        public String link_count
        {
            get
            {
                return this.link_countField;
            }
            set
            {
                this.link_countField = value;
            }
        }

        /// <remarks/>
        public String going_count
        {
            get
            {
                return this.going_countField;
            }
            set
            {
                this.going_countField = value;
            }
        }

        /// <remarks/>
        public String watching_count
        {
            get
            {
                return this.watching_countField;
            }
            set
            {
                this.watching_countField = value;
            }
        }

        /// <remarks/>
        public string created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        /// <remarks/>
        public string modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }

        /// <remarks/>
        public searchEventPerformers performers
        {
            get
            {
                return this.performersField;
            }
            set
            {
                this.performersField = value;
            }
        }

        /// <remarks/>
        public searchEventImage image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        public String privacy
        {
            get
            {
                return this.privacyField;
            }
            set
            {
                this.privacyField = value;
            }
        }

        /// <remarks/>
        public object calendars
        {
            get
            {
                return this.calendarsField;
            }
            set
            {
                this.calendarsField = value;
            }
        }

        /// <remarks/>
        public object groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("user", IsNullable = false)]
        public searchEventUser[] going
        {
            get
            {
                return this.goingField;
            }
            set
            {
                this.goingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventPerformers
    {

        private searchEventPerformersPerformer performerField;

        /// <remarks/>
        public searchEventPerformersPerformer performer
        {
            get
            {
                return this.performerField;
            }
            set
            {
                this.performerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventPerformersPerformer
    {

        private string idField;

        private string urlField;

        private string nameField;

        private string short_bioField;

        private string creatorField;

        private string linkerField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string short_bio
        {
            get
            {
                return this.short_bioField;
            }
            set
            {
                this.short_bioField = value;
            }
        }

        /// <remarks/>
        public string creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }

        /// <remarks/>
        public string linker
        {
            get
            {
                return this.linkerField;
            }
            set
            {
                this.linkerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventImage
    {

        private string urlField;

        private String widthField;

        private String heightField;

        private object captionField;

        private searchEventImageThumb thumbField;

        private searchEventImageSmall smallField;

        private searchEventImageMedium mediumField;

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public String width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public String height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public object caption
        {
            get
            {
                return this.captionField;
            }
            set
            {
                this.captionField = value;
            }
        }

        /// <remarks/>
        public searchEventImageThumb thumb
        {
            get
            {
                return this.thumbField;
            }
            set
            {
                this.thumbField = value;
            }
        }

        /// <remarks/>
        public searchEventImageSmall small
        {
            get
            {
                return this.smallField;
            }
            set
            {
                this.smallField = value;
            }
        }

        /// <remarks/>
        public searchEventImageMedium medium
        {
            get
            {
                return this.mediumField;
            }
            set
            {
                this.mediumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventImageThumb
    {

        private string urlField;

        private String widthField;

        private String heightField;

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public String width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public String height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventImageSmall
    {

        private string urlField;

        private String widthField;

        private String heightField;

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public String width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public String height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventImageMedium
    {

        private string urlField;

        private String widthField;

        private String heightField;

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public String width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public String height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class searchEventUser
    {

        private object usernameField;

        /// <remarks/>
        public object username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
}